### PR TITLE
Add static site generator

### PR DESCRIPTION
**Pull request by mpharrigan**
cc #15

### CODE REVIEW

**Comment by mpharrigan** [comment]
Alright, this is in a workable state. We'll have to test the travis build / deployment by merging (later). I added the markdown files from https://github.com/choderalab/openmm7tutorials to see what we had to work with.

I changed the filenames from `README.md` to `index.md` and changed the titles of the pages into the following jekyll yaml front-matter:

```
---
layout: nicepage
title: Alchemical Free Energy Example
lead: Optionally put a lead here
---
```

@jchodera : how do you plan to continue developing the tutorials? Do you plan on finalizing them in their current repo and then we can port things here, or do you want to develop in the context of jekyll rendering

Also please try forking from this branch and see if you can build the tutorials. It would be best if your group had the ability to preview what the rendered pages look like.

screenshot from 2017-03-21 13 40 53

**Comment by jchodera** [comment]
> Alright, this is in a workable state. We'll have to test the travis build / deployment by merging (later). I added the markdown files from https://github.com/choderalab/openmm7tutorials to see what we had to work with.

This looks great!

> @jchodera : how do you plan to continue developing the tutorials? Do you plan on finalizing them in their current repo and then we can port things here, or do you want to develop in the context of jekyll rendering

We can do either. Eventually, it would be nice to be able to have the code snippets be automatically tested, but I'm not quite sure how best to do that at this stage. We could therefore just switch to editing the files in the online tutorials to minimize effort.

> Also please try forking from this branch and see if you can build the tutorials. It would be best if your group had the ability to preview what the rendered pages look like.

Will do!

Tagging @chayast and @rafwiewiora.

**Comment by jchodera** [comment]
Just a heads-up to @mpharrigan @peastman @chayast @rafwiewiora that we should try to get this cleaned up and working to replace the current openmm.org with a Jekyll-based static site generator containing tutorials since the paper is going into production soon.

We'll also want to merge in the final versions of all the tutorials at https://github.com/choderalab/openmm7tutorials

I have on my TODO list the creation of some simpler tutorials for more basic operations requested by others at the CADD GRC.

**Comment by mpharrigan** [comment]
Hi, I haven't worked on this since March and my time is allocated to other projects now. I won't be able to contribute any code, but I believe this PR is 99% complete other than the actual content of the tutorials. I would imagine the best thing to do would be to branch off of this PR and copy the updated tutorial files over (but don't overwrite the jekyll front-matter)

**Comment by jchodera** [comment]
This can be closed in favor of #19.

**Pull request closed without merging**
